site:
  locale: en
  meta_description: some meta description
  meta_keywords: some meta keywords
  name: webage
  seo_title: coresystems
  pages:
  - index:
      cache_strategy: none
      published: true
      title: Home page
      listed: true
  - china_team:
      cache_strategy: none
      published: true
      title: China team
      listed: true
      editable_elements:
      - block: content
        slug: china team
        content: ""
  - company:
      cache_strategy: none
      published: true
      title: Company
      listed: true
      editable_elements:
      - block: content
        slug: coresystems global
        content: ""
      - block: content
        slug: coresystems description
        content: ""
      - block: content
        slug: coresystems shanghai
        content: ""
      - block: content
        slug: coresystems shanghai description
        content: ""
      - block: content
        slug: sucess stories
        content: ""
      - block: content
        slug: sucess stories description
        content: ""
  - partner:
      cache_strategy: none
      published: true
      title: Partner
      listed: true
      editable_elements:
      - block: content
        slug: Devices
        content: ""
  - products:
      cache_strategy: none
      published: true
      title: Products
      listed: true
  - service:
      cache_strategy: none
      published: true
      title: Service
      listed: true
      editable_elements:
      - block: content
        slug: Devices
        content: ""
  - starter_guide:
      cache_strategy: none
      published: true
      title: Starter guide
      listed: true
  - success_story:
      cache_strategy: none
      published: true
      title: Success story
      listed: true
      editable_elements:
      - block: content
        slug: sucess story
        content: ""
  - company_overview:
      cache_strategy: none
      published: true
      title: Company overview
      listed: true
      editable_elements:
      - block: content
        slug: company description
        content: ""
  - download_area:
      cache_strategy: none
      published: true
      title: Download area
      listed: true
  - mobile_solution:
      cache_strategy: none
      published: true
      title: Mobile solution
      listed: true
      editable_elements:
      - block: content
        slug: service_text
        content: ""
  - "404":
      cache_strategy: none
      published: true
      title: Page not found
      listed: true
  content_types:
    newsfeed:
      description: news feed for the front page
      name: newsfeed
      order_by: created_at
      order_direction: asc
      slug: newsfeed
      highlighted_field_name: news
      fields:
      - news:
          required: true
          label: news
          kind: text
      contents:
      - <p>this is the newsfeed for coresystems china</p>: {}

      - <p>this is the second news for coresystems front page</p>: {}

    slide_images:
      name: slide_images
      order_by: created_at
      order_direction: asc
      slug: slide_images
      highlighted_field_name: image
      fields:
      - image:
          kind: file
          label: image
          required: true
      - banner:
          label: banner
          kind: text
      contents:
      - /sites/4f384a73930c556f4c000005/contents/content_instance/4f5f443fc61a03122700003d/files/frontpage_top_section_image1.jpg:
          banner: "<p>\xE9\xB9\xA4\xE9\xB8\xA3\xE8\xBD\xAF\xE4\xBB\xB6\xE4\xBA\x9A\xE5\xA4\xAA\xE6\x8D\xAE\xE7\x82\xB9</p>"
      - /sites/4f384a73930c556f4c000005/contents/content_instance/4f5f4eaec61a031c8e00003a/files/test3_small_copy.png:
          banner: "<p>\xE5\xBE\x88\xE9\x85\xB7\xE7\x9A\x84\xE5\x95\x86\xE5\x8A\xA1\xE8\xBD\xAF\xE4\xBB\xB6</p>"
      - /sites/4f384a73930c556f4c000005/contents/content_instance/4f5f4ed1c61a031c8e00003c/files/test4_small_copy.png:
          banner: "<p>\xE6\x89\xBF\xE8\xAF\xBA\xE9\xAB\x98\xE5\x93\x81\xE8\xB4\xA8\xE6\x9C\x8D\xE5\x8A\xA1</p>"